export const COPY = {
  ALERTS: {
    WALKIN_SUCCESS: 'บันทึก Walk-in สำเร็จ!',
    UPDATE_CAPACITY_SUCCESS: 'อัปเดตจำนวนที่นั่งสำเร็จ',
    APPROVE_SLIP_SUCCESS: (credits: number, name: string) => `อนุมัติสำเร็จ — เพิ่ม ${credits} เครดิตให้น้อง${name}`,
    ERROR_GENERIC: (msg: string) => `Error: ${msg}`,
    NO_SESSION_YET: 'ยังไม่มี session สำหรับวันนี้ — สร้างเมื่อมีการจองหรือ walk-in',
    INVALID_CAPACITY: 'กรุณาระบุจำนวนที่นั่งที่ถูกต้อง',
    NO_SESSION_FOUND: 'ยังไม่มี session สำหรับวันนี้',
    FILE_TOO_LARGE: (mb: number) => `ขนาดไฟล์ต้องไม่เกิน ${mb}MB`,
    REQUIRE_ALL_FIELDS: 'กรุณากรอกข้อมูลให้ครบ',
    CANNOT_DELETE: (msg: string) => `ลบไม่ได้: ${msg}`,
    SELECT_DATE_REQUIRED: 'กรุณาเลือกวันที่',
    SAVE_SUCCESS: 'บันทึกข้อมูลเรียบร้อยแล้ว',
    REQUIRE_NAME_PHONE: 'กรุณาระบุชื่อและเบอร์โทรศัพท์ให้ครบถ้วน',
    REQUIRE_ADJUST_REASON: 'กรุณาระบุเหตุผลในการปรับเครดิต',
  },
  EMPTY_STATES: {
    NO_PARENTS: 'ไม่พบข้อมูลผู้ปกครอง',
    NO_CREDIT_HISTORY: 'ยังไม่มีประวัติเครดิต',
    NO_PENDING_SLIPS: 'ไม่มีสลิปที่รอตรวจสอบ (All caught up!)',
    NO_STUDENTS: 'ไม่มีนักเรียนในรอบนี้',
    NO_CHILDREN: 'ไม่พบข้อมูลนักเรียน',
  },
  LOADING: {
    DEFAULT: 'กำลังโหลดข้อมูล...',
    SHORT: 'กำลังโหลด...',
  },
  RULES: {
    UPLOAD_LIMIT_HINT: (types: string, mb: number) => `${types} — ไม่เกิน ${mb}MB`,
    NO_CANCEL_AFTER_XAM: (hour: number) => `ระบบจะปิดรับจองและไม่อนุญาตให้ยกเลิกสิทธิ์ ในวันที่มีการเรียนการสอนเวลา ${String(hour).padStart(2, '0')}:00 น. เป็นต้นไป`,
  },
  AUTH: {
    EMAIL_LABEL: 'อีเมล',
    PASSWORD_LABEL: 'รหัสผ่าน',
    NAME_LABEL: 'ชื่อ-นามสกุล',
    PHONE_LABEL: 'เบอร์โทรศัพท์',
    SIGN_IN_BTN: 'Sign In (เข้าสู่ระบบ)',
    SIGN_UP_BTN: 'Sign Up (ลงทะเบียนใหม่)',
    SIGNING_IN: 'กำลังตรวจสอบข้อมูล...',
    SIGNING_UP: 'กำลังสร้างบัญชีผู้ใช้งาน...',
  },
  BOOKING_FLOW: {
    STEP_1: '1. เลือกรายชื่อนักเรียน',
    STEP_2: '2. เลือกวันที่เรียน',
    STEP_3: '3. สรุปการจองสิทธิ์',
    NO_CHILDREN: '-- ยังไม่มีรายชื่อนักเรียน --',
    UPCOMING_CLASSES: 'รอบที่จองไว้ (Upcoming Classes)',
    SESSION_MORNING: 'เช้า (09:00 - 12:00)',
    NOT_ALLOWED: 'ไม่อนุญาต',
    SELECT_DATE_HINT: 'กรุณาแตะเลือกวันที่ในปฏิทิน',
    ADVANCE_NOTICE: '* ระบบแสดงรอบเรียนล่วงหน้า 2 เดือน',
    DATE_LABEL: 'วันที่เรียน:',
    STUDENT_LABEL: 'นักเรียน:',
    STATUS_LABEL: 'สถานะ:',
    SELECT_SESSION_LABEL: 'เลือกรอบเวลา:',
    CONFIRM_BOOKING_BTN: 'ยืนยันการจองสิทธิ์ (หัก 1 Credit)',
    CONFIRM_BOOKING_TITLE: 'ยืนยันการจองสิทธิ์?',
    DEDUCT_NOTICE: 'ระบบจะหักสิทธิ์',
    CREDIT_LABEL: 'Credit',
    FROM_PACKAGE: 'จากแพ็กเกจของคุณ',
    REMAINING_CREDITS: 'สิทธิ์เรียน:',
    CREDIT_UNIT: 'ครั้ง',
    CANCEL_TITLE: 'ยกเลิกสำเร็จ',
    CONFIRM_CANCEL_TITLE: 'ยืนยันการยกเลิก?',
    REFUND_NOTICE: 'ระบบจะทำการยกเลิกสิทธิ์และ',
    REFUND_HIGHLIGHT: 'คืนเครดิตให้ 1 ครั้ง',
  },
  APPLY_FLOW: {
    SUCCESS_TITLE: 'ลงทะเบียนสำเร็จ!',
    GO_TO_CALENDAR_BTN: 'ไปที่ปฏิทินจองคลาส',
    PHOTO_TITLE: 'รูปถ่ายสำหรับการทดลองเรียน',
    PHOTO_PARENT_HINT: 'รูปถ่ายผู้ปกครองเดี่ยวชัดเจน',
    PHOTO_CHILD_HINT: 'รูปถ่ายบุตรหลานเดี่ยวชัดเจน (ไม่ใส่แว่นกันแดดหรือหมวก)',
    UPLOAD_LIMIT: 'อัปโหลดไฟล์ที่รองรับ 1 รายการ ขนาดสูงสุด 10 MB',
    TRANSFER_INSTRUCTION: 'กรุณาโอนเงินชำระไปยังบัญชีใดบัญชีหนึ่งของโรงเรียนและแนบหลักฐานการโอนด้านล่างนี้',
    TOPUP_TITLE: 'เพิ่มสิทธิ์เพื่อจองคลาสเรียนเพลย์กรุ๊ป',
    SELECT_PACKAGE: '-- เลือกแพ็กเกจ --',
    UPLOAD_SLIP: 'อัปโหลดสลิปโอนเงิน',
  }
};
